### ISSUE TITLE
Missing Log File when setting up Rumal

### ISSUE THREAD

**Issue by satwik77** [thugs-rumal/rumal#19]
The Issue:
On setting up Rumal for the first time the fdaemon is not able to run due to missing log file.

```
  Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 71, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 2] No such file or directory: '/home/gauss/gitnew/rumal/logs/log.log'
```

How to Reproduce:

`python manage.py fdaemon` inside the root folder while setting up a new instance of Rumal.

Suggested Fix:
 Create a blank file 'log.log' in a new directory 'logs'. I also noticed that the logs folder is part of .gitignore but I feel that we should add a blank file.

**Comment by pdelsante** [comment]
I would bet that the problem is not in the missing `logs/log.log` file, but rather in the missing `logs` directory: you had to create it to be able to put the file in place, and that was what fixed the problem.

I should have fixed it now, could you please try again?

**Comment by satwik77** [comment]
Sorry, it worked with creating a blank `logs/log.log` file so I went on with it, but you are right I should have only created the `logs` directory.
