### ISSUE TITLE
No connection adapters were found for '"http://backend:8000"/api/v1/task/'

### ISSUE THREAD

**Issue by gurre** [thugs-rumal/rumal#30]
There seems to be an issue when the frontend is trying to connect to the backend, When an URL is submitted a traceback is printed to /var/log/rumal-fdaemon.log.

```
$ docker-compose exec frontend /bin/bash -c "cat /var/log/rumal-fdaemon.log"
2016-06-02 08:08:29 UTC [interface.management.commands.fdaemon] DEBUG: Starting up frontend daemon
2016-06-02 08:08:29 UTC [interface.management.commands.fdaemon] DEBUG: Fetching new tasks to post to backend.
2016-06-02 08:08:29 UTC [interface.management.commands.fdaemon] DEBUG: Got 1 new tasks
2016-06-02 08:08:29 UTC [interface.management.commands.fdaemon] DEBUG: Posting task 1
Traceback (most recent call last):
  File "/opt/rumal/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/opt/rumal/interface/management/commands/fdaemon.py", line 217, in handle
    self.post_new_task(task)
  File "/opt/rumal/interface/management/commands/fdaemon.py", line 111, in post_new_task
    r = requests.post(TASK_POST_URL, json.dumps(temp), headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 579, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 653, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '"http://backend:8000"/api/v1/task/'
```

There seems to be a related issue on stackoverflow [Requests : No connection adapters were found for, error in Python3](http://stackoverflow.com/questions/29386783/requests-no-connection-adapters-were-found-for-error-in-python3).

Root cause seems to be this [Python ConfigParser - values between quotes](http://stackoverflow.com/questions/1311367/python-configparser-values-between-quotes).

Line in source code:
[BACKEND_HOST = config.get('backend', 'host', 'http://localhost:8080')](https://github.com/thugs-rumal/rumal/blob/master/interface/management/commands/fdaemon.py#L49)

The host line is created as such:

```
# Create the needed configuration files
echo "[backend]" > /opt/rumal/conf/backend.conf
echo 'host = "http://backend:8000"' >> /opt/rumal/conf/backend.conf
```

Removing the double quotes seems to fix it.

**Comment by Dennisparchkov** [comment]
Your solution is correct for this issue but from #31 the frontend no longer uses REST API to communicate with backend. Rabbitmq communication has been implemented. This issue can be closed.
